In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:

dev_df = pd.read_csv('../data/assignment1_dev_set.csv')
val_df = pd.read_csv('../data/assignment1_val_set.csv')

# Display basic info of the dataframe, their statistics and missing values

display(dev_df.info())
display(dev_df.head())
display(dev_df.describe())
print("dev set missing values: " + str(dev_df.isnull().sum().sum()))

display(val_df.info())
display(val_df.head())
display(val_df.describe())
print("val set missing values: " + str(val_df.isnull().sum().sum()))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Columns: 141 entries, Unnamed: 0 to Ruminococcus gnavus
dtypes: float64(136), int64(1), object(4)
memory usage: 538.8+ KB

None

,Unnamed: 0,Project ID,Experiment type,Sex,Host age,BMI,Disease MESH ID,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
0,0,PRJEB11419,Metagenomics,Male,53.0,19.01,D006262,0.000000,0.000000,0.000000,...,0.005891,0.029457,0.000000,0.000000,0.002946,0.000000,0.000000,0.000000,0.002946,0.100153
1,1,PRJNA388263,Metagenomics,Female,21.0,23.50,D006262,0.001028,0.000000,0.000000,...,0.000000,0.002569,0.412652,0.003083,0.000000,0.000000,0.008736,0.014903,0.077597,0.004625
2,2,PRJNA388263,Metagenomics,Male,52.0,25.80,D006262,0.001406,0.000000,0.000000,...,0.000000,0.005624,0.002812,0.007031,0.000000,0.000000,0.000000,0.000000,0.005624,0.016873
3,3,PRJEB11419,Metagenomics,Female,40.0,23.49,D006262,0.000000,0.008825,0.273562,...,0.017649,0.198553,0.000000,0.158842,0.030886,0.101483,0.000000,0.000000,0.000000,0.000000
4,4,PRJEB11419,Metagenomics,Female,30.0,22.60,D006262,0.002878,0.037419,7.359970,...,0.305106,0.135283,0.000000,0.051811,0.054689,0.083473,0.020148,0.000000,0.054689,0.011513

,Unnamed: 0,Host age,BMI,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,Actinomyces lingnae,Akkermansia muciniphila,Alistipes finegoldii,Alistipes indistinctus,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
count,489.000000,489.000000,489.00000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,...,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000
mean,244.000000,46.703497,24.93955,0.016818,0.029968,0.294917,0.001608,1.555914,0.249606,0.061796,...,0.029822,0.247603,0.032148,0.097871,0.052936,0.038531,0.006565,0.012565,0.041855,0.091976
std,141.306405,15.728231,4.20771,0.145035,0.197816,0.804704,0.010431,4.306539,0.630670,0.239054,...,0.090605,0.490321,0.180606,0.197044,0.310313,0.122225,0.018357,0.097056,0.181979,0.416085
min,0.000000,19.000000,16.97000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,122.000000,31.000000,22.38000,0.000000,0.000000,0.000000,0.000000,0.003438,0.003380,0.000000,...,0.000000,0.002570,0.000000,0.004881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,244.000000,52.000000,25.10000,0.000000,0.000000,0.001109,0.000000,0.034284,0.044961,0.000000,...,0.000260,0.047224,0.000000,0.029362,0.000000,0.001687,0.000000,0.000000,0.003266,0.007035
75%,366.000000,58.000000,25.80000,0.000000,0.000000,0.129398,0.000000,0.820242,0.188550,0.045111,...,0.027723,0.303173,0.005768,0.100294,0.015439,0.018352,0.005693,0.000000,0.020020,0.020978
max,488.000000,81.000000,67.26000,2.861300,2.622820,7.660350,0.206426,38.834900,6.068670,4.478660,...,1.465160,3.714530,3.118150,1.801190,4.726220,1.173380,0.273194,1.939150,2.478070,6.752840

dev set missing values: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Columns: 141 entries, Unnamed: 0 to Ruminococcus gnavus
dtypes: float64(136), int64(1), object(4)
memory usage: 232.6+ KB

None

,Unnamed: 0,Project ID,Experiment type,Sex,Host age,BMI,Disease MESH ID,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
0,0,PRJEB11419,Metagenomics,Male,60.0,25.71,D006262,0.0,0.000000,1.621960,...,0.000000,2.871240,0.0,0.068238,0.115479,0.015747,0.010498,0.000000,0.010498,0.551152
1,1,PRJNA379979,Metagenomics,Male,57.0,27.20,D006262,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,PRJEB11419,Metagenomics,Male,65.0,22.35,D006262,0.0,0.002095,0.000000,...,0.000000,0.064936,0.0,0.016758,0.000000,0.041895,0.010474,0.006284,0.014663,0.000000
3,3,PRJEB11419,Metagenomics,Male,55.0,25.52,D006262,0.0,0.000000,0.044998,...,0.003461,0.089996,0.0,0.003461,0.006923,0.000000,0.000000,0.020768,0.034614,0.013846
4,4,PRJNA379979,Metagenomics,Female,54.0,21.60,D006262,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

,Unnamed: 0,Host age,BMI,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,Actinomyces lingnae,Akkermansia muciniphila,Alistipes finegoldii,Alistipes indistinctus,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
count,211.00000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,...,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000
mean,105.00000,46.303318,24.800853,0.028603,0.007540,0.333079,0.006520,1.275855,0.256110,0.056868,...,0.023161,0.231486,0.036935,0.102440,0.031075,0.049638,0.006270,0.012285,0.017258,0.131753
std,61.05462,16.056832,3.987255,0.209176,0.049924,0.857101,0.052926,3.757554,0.800050,0.239581,...,0.061168,0.539919,0.204636,0.210114,0.133408,0.210740,0.013510,0.117794,0.039845,0.661640
min,0.00000,19.000000,16.970000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,52.50000,31.000000,22.220000,0.000000,0.000000,0.000000,0.000000,0.002942,0.002488,0.000000,...,0.000000,0.002643,0.000000,0.001640,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,105.00000,52.000000,25.100000,0.000000,0.000000,0.001429,0.000000,0.044957,0.057409,0.000000,...,0.000000,0.046365,0.000000,0.024696,0.000000,0.003468,0.000000,0.000000,0.002977,0.005630
75%,157.50000,57.000000,25.800000,0.000000,0.000000,0.112273,0.000833,0.560304,0.198418,0.025187,...,0.017703,0.267308,0.006942,0.108798,0.010384,0.022265,0.005369,0.000000,0.015401,0.019473
max,210.00000,79.000000,45.200000,2.740080,0.565065,4.708840,0.645116,32.133600,9.857790,3.187810,...,0.549399,5.549120,2.708990,1.726760,1.683160,2.310910,0.086478,1.696490,0.325267,6.537770

val set missing values: 0

In [3]:
# Check for columns containing only one value

for column in dev_df.columns:
    num_unique = dev_df[column].nunique()
    if num_unique == 1:
        print(f"dev: Column '{column}' has only 1 unique value: {dev_df[column].iloc[0]}")

for column in val_df.columns:
    num_unique = val_df[column].nunique()
    if num_unique == 1:
        print(f"val: Column '{column}' has only 1 unique value: {val_df[column].iloc[0]}")

dev: Column 'Experiment type' has only 1 unique value: Metagenomics
dev: Column 'Disease MESH ID' has only 1 unique value: D006262
val: Column 'Experiment type' has only 1 unique value: Metagenomics
val: Column 'Disease MESH ID' has only 1 unique value: D006262
val: Column 'Ruminococcaceae bacterium D16' has only 1 unique value: 0.0

In [4]:
# Drop the irrelevant columns
dev_df_2 = dev_df.drop(columns=['Unnamed: 0', 'Project ID', 'Experiment type', 'Disease MESH ID'])


val_df_2 = val_df.drop(columns=['Unnamed: 0', 'Project ID', 'Experiment type', 'Disease MESH ID'])

display(dev_df_2.head())
display(val_df_2.head())

,Sex,Host age,BMI,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,Actinomyces lingnae,Akkermansia muciniphila,Alistipes finegoldii,Alistipes indistinctus,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
0,Male,53.0,19.01,0.000000,0.000000,0.000000,0.000000,0.017674,0.000000,0.00000,...,0.005891,0.029457,0.000000,0.000000,0.002946,0.000000,0.000000,0.000000,0.002946,0.100153
1,Female,21.0,23.50,0.001028,0.000000,0.000000,0.000000,13.015800,0.001542,0.00000,...,0.000000,0.002569,0.412652,0.003083,0.000000,0.000000,0.008736,0.014903,0.077597,0.004625
2,Male,52.0,25.80,0.001406,0.000000,0.000000,0.001406,0.002812,0.201074,0.00000,...,0.000000,0.005624,0.002812,0.007031,0.000000,0.000000,0.000000,0.000000,0.005624,0.016873
3,Female,40.0,23.49,0.000000,0.008825,0.273562,0.000000,0.044123,0.004412,0.34857,...,0.017649,0.198553,0.000000,0.158842,0.030886,0.101483,0.000000,0.000000,0.000000,0.000000
4,Female,30.0,22.60,0.002878,0.037419,7.359970,0.000000,0.872143,0.000000,0.00000,...,0.305106,0.135283,0.000000,0.051811,0.054689,0.083473,0.020148,0.000000,0.054689,0.011513

,Sex,Host age,BMI,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,Actinomyces lingnae,Akkermansia muciniphila,Alistipes finegoldii,Alistipes indistinctus,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
0,Male,60.0,25.71,0.0,0.000000,1.621960,0.0,0.000000,0.068238,0.020996,...,0.000000,2.871240,0.0,0.068238,0.115479,0.015747,0.010498,0.000000,0.010498,0.551152
1,Male,57.0,27.20,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Male,65.0,22.35,0.0,0.002095,0.000000,0.0,0.002095,0.041895,0.000000,...,0.000000,0.064936,0.0,0.016758,0.000000,0.041895,0.010474,0.006284,0.014663,0.000000
3,Male,55.0,25.52,0.0,0.000000,0.044998,0.0,0.013846,0.010384,0.000000,...,0.003461,0.089996,0.0,0.003461,0.006923,0.000000,0.000000,0.020768,0.034614,0.013846
4,Female,54.0,21.60,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [5]:
# Use LabelEncoder to convert categorical columns to numerical values

# label_encoder = LabelEncoder()
# label_encoder.classes_ = np.array(['Male', 'Female'])
# dev_df_3 = dev_df_2
# for column in dev_df_2.select_dtypes(include=['object']).columns:
#     dev_df_3[column] = label_encoder.fit_transform(dev_df_2[column])



# val_df_3=val_df_2
# for column in val_df_2.select_dtypes(include=['object']).columns:
#     val_df_3[column] = label_encoder.fit_transform(val_df_2[column])

dev_df_3 = dev_df_2
dev_df_3['Sex'] = dev_df_3['Sex'].map({'Male': 0, 'Female': 1})

val_df_3=val_df_2
val_df_3['Sex'] = val_df_3['Sex'].map({'Male': 0, 'Female': 1})

# display(dev_df_3.info())
# display(dev_df_3.head())

# display(val_df_3.info())
# display(val_df_3.head())

In [6]:
# dev_df_3.hist(figsize=(40, 40))
# plt.show()

In [7]:
scaler = StandardScaler()
col_scale = [x for x in dev_df_3.columns if x not in ['BMI', 'Sex']]

dev_df_3[col_scale] = scaler.fit_transform(dev_df_3[col_scale])

val_df_3[col_scale] = scaler.fit_transform(val_df_3[col_scale])


display(dev_df_3.info())
display(dev_df_3.head())

display(val_df_3.info())
display(val_df_3.head())

dev_df_3.to_csv('../data/development_final_data.csv.csv', index=False)  
val_df_3.to_csv('../data/evaluation_final_data.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Columns: 137 entries, Sex to Ruminococcus gnavus
dtypes: float64(136), int64(1)
memory usage: 523.5 KB

None

,Sex,Host age,BMI,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,Actinomyces lingnae,Akkermansia muciniphila,Alistipes finegoldii,Alistipes indistinctus,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
0,0,0.400741,19.01,-0.116074,-0.151651,-0.366867,-0.154353,-0.357553,-0.396184,-0.258769,...,-0.264395,-0.445361,-0.178185,-0.497202,-0.161263,-0.315570,-0.357998,-0.129594,-0.214033,0.019673
1,1,-1.635900,23.50,-0.108980,-0.151651,-0.366867,-0.154353,2.663768,-0.393737,-0.258769,...,-0.329484,-0.500254,2.108974,-0.481538,-0.170765,-0.315570,0.118380,0.024110,0.196608,-0.210150
2,0,0.337096,25.80,-0.106369,-0.151651,-0.366867,-0.019414,-0.361007,-0.077031,-0.258769,...,-0.329484,-0.494017,-0.162598,-0.461486,-0.170765,-0.315570,-0.357998,-0.129594,-0.199298,-0.180683
3,1,-0.426644,23.49,-0.116074,-0.106995,-0.026565,-0.154353,-0.351405,-0.389180,1.200847,...,-0.134492,-0.100140,-0.178185,0.309746,-0.071131,0.515577,-0.357998,-0.129594,-0.230236,-0.221277
4,1,-1.063095,22.60,-0.096208,0.037702,8.788685,-0.154353,-0.158938,-0.396184,-0.258769,...,3.041408,-0.229310,-0.178185,-0.233995,0.005653,0.368071,0.740698,-0.129594,0.070595,-0.193578

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Columns: 137 entries, Sex to Ruminococcus gnavus
dtypes: float64(136), int64(1)
memory usage: 226.0 KB

None

,Sex,Host age,BMI,Acholeplasma axanthum,Acidaminococcus fermentans,Acidaminococcus intestini,Actinomyces lingnae,Akkermansia muciniphila,Alistipes finegoldii,Alistipes indistinctus,...,Clostridium sphenoides,Clostridium spiroforme,Clostridium stercorarium,Clostridium symbiosum,Clostridium thermosuccinogenes,Clostridium xylanolyticum,Eubacterium brachy,Eubacterium dolichum,Eubacterium sulci,Ruminococcus gnavus
0,0,0.855041,25.71,-0.137066,-0.151394,1.507344,-0.123487,-0.340352,-0.235384,-0.150081,...,-0.379542,4.900793,-0.180919,-0.163163,0.634181,-0.161203,0.313723,-0.104544,-0.170046,0.635386
1,0,0.667761,27.20,-0.137066,-0.151394,-0.389535,-0.123487,-0.340352,-0.320879,-0.237927,...,-0.379542,-0.429761,-0.180919,-0.488701,-0.233484,-0.236104,-0.465205,-0.104544,-0.434144,-0.199604
2,0,1.167176,22.35,-0.137066,-0.109337,-0.389535,-0.123487,-0.339793,-0.268389,-0.237927,...,-0.379542,-0.309204,-0.180919,-0.408756,-0.233484,-0.036834,0.311906,-0.051068,-0.065268,-0.199604
3,0,0.542907,25.52,-0.137066,-0.151394,-0.336909,-0.123487,-0.336658,-0.307868,-0.237927,...,-0.322818,-0.262680,-0.180919,-0.472188,-0.181469,-0.236104,-0.465205,0.072187,0.436634,-0.178628
4,1,0.480480,21.60,-0.137066,-0.151394,-0.389535,-0.123487,-0.340352,-0.320879,-0.237927,...,-0.379542,-0.429761,-0.180919,-0.488701,-0.233484,-0.236104,-0.465205,-0.104544,-0.434144,-0.199604

# -----------------------------------------------------------

In [8]:
# # Assuming the last column is the target variable
# X = dev_df.iloc[:, :-1].values
# y = dev_df.iloc[:, -1].values

In [9]:
# # Use LabelEncoder to convert categorical columns to numerical values
# label_encoder = LabelEncoder()
# for column in dev_df.select_dtypes(include=['object']).columns:
#     dev_df[column] = label_encoder.fit_transform(dev_df[column])